<a href="https://colab.research.google.com/github/w2j1y12/pdm17/blob/main/numpy/numpy_0_why_use_it.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy  
## What is numpy?  
* python module to do math!  
    - random number
    - array -> ndarray
    - math operations
    - ...

#### Why do data coders use & enjoy it?

In [3]:
a=range(10)

range(0, 10)

In [4]:
a

range(0, 10)

In [5]:
la=list(a)
la

# 제일 마지막에 입련된 것이 출력

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

> 그러면 리스트 각 요소를 2배, 또는 5배로 변경하는 방법은?

In [6]:
2*la

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 우리가 원하는 결과가 아니다.

In [7]:
[2 * i for i in la]

# la라는 리스트의 요소 i에서 5(2)를 곱해라
# 머신러닝에서 자주 사용 -> 잘 알아둬래

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
import numpy as np

In [8]:
la

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
larr = np.array(la)
larr   # broadcasted multiplication

# numpy 배열을 만드는 것

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
larr * 5

# 각 요소가 곱해져서 나옴

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
# Try below!
la = np.array(a)
la

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy가 데이터 코딩, 특히 딥러닝에 이용되는 예제

> http://life21c.inje.ac.kr:8501/


- numpy array vs. list

    *  머신러닝에서 숫자, 사람, 동물 등의 인식을 하기 위해서는 이미지 데이터를 행렬(matrix)로 변환하는 것이 중요하다.
    *  행렬을 나타내기 위해서는 list를 사용할 수도 있지만, 행렬 연산이 직관적이지 않고 오류 가능성이 높기 때문에 **행렬 연산을 위해서는 numpy 사용이 필수적**이다.

---